# SPDX-FileCopyrightText: 2022 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
name: Install dependencies and prepare the environment.
description: Install the necessary dependencies for jobs.
runs:
  using: composite
  steps:
    - name: Install pipenv.
      run: pipx install pipenv
      shell: bash

    - name: Set up Python 3.
      uses: actions/setup-python@v3
      id: setup-python
      with:
        python-version: '3.9'
        cache: 'pipenv'

    - name: Install dependencies via pipenv.
      run: pipenv install --dev
      shell: bash
